directory:
- .
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework: all
skip-check:
- CKV_AWS_158 #"Ensure that CloudWatch Log Group is encrypted by KMS"
- CKV_AWS_66 #"Ensure that CloudWatch Log Group specifies retention days"
